a6_codecept_is_awesome_homepage:
    path:     /
    defaults: { _controller: A6CodeceptIsAwesomeBundle:Home:index }

a6_codecept_is_awesome_secured_area:
    path:     /secured-area
    defaults: { _controller: A6CodeceptIsAwesomeBundle:SecuredArea:securedIndex }