parameters:
#    a6_codecept_is_awesome.service.fizz_buzz.class: A6\CodeceptIsAwesomeBundle\Service\FizzBuzz

services:
#    a6_codecept_is_awesome.service.fizz_buzz:
#        class: %a6_codecept_is_awesome.service.fizz_buzz.class%


